# Generated by Django 3.1.5 on 2021-02-10 18:10

from django.db import migrations, models
import django.db.models.deletion
import users.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40)),
                ('email', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=40)),
                ('country', models.CharField(max_length=30)),
                ('image', models.FileField(blank=True, max_length=255, null=True, upload_to=users.models.get_cover_path)),
                ('done_recipes', models.ManyToManyField(related_name='done', to='recipes.Recipe')),
                ('liked_recipes', models.ManyToManyField(related_name='liked', to='recipes.Recipe')),
                ('recipes', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='recipes.recipe')),
            ],
        ),
    ]
