# Generated by Django 3.1.7 on 2021-03-10 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0002_auto_20210309_2153'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='instructions',
        ),
        migrations.AddField(
            model_name='recipe',
            name='expiry',
            field=models.CharField(default='', max_length=128),
        ),
    ]
