# Generated by Django 3.1.6 on 2021-02-18 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0002_auto_20210211_1203'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='description',
            field=models.CharField(default='', max_length=256),
        ),
    ]
