# Generated by Django 3.1.5 on 2021-03-10 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0002_auto_20210310_1431'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='instructions',
            field=models.JSONField(default='[]'),
            preserve_default=False,
        ),
    ]
