# Generated by Django 3.1.5 on 2021-03-17 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0003_recipe_instructions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='description',
            field=models.TextField(default='', max_length=512),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='instructions',
            field=models.JSONField(default=dict),
        ),
    ]
