# Generated by Django 3.1.7 on 2021-03-10 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredient', '0003_amount_ingredient'),
        ('recipe', '0003_auto_20210310_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(to='ingredient.Amount'),
        ),
    ]
