# Generated by Django 3.1.7 on 2021-03-10 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utensil', '0002_utensilamount'),
        ('recipe', '0004_auto_20210310_1332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='utensils',
            field=models.ManyToManyField(to='utensil.UtensilAmount'),
        ),
    ]
