# Generated by Django 3.1.7 on 2021-03-10 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0005_auto_20210310_1346'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='notes_from_author',
            field=models.CharField(default='', max_length=256),
        ),
    ]
