# Generated by Django 3.2 on 2021-06-01 16:48
from django.contrib.postgres.operations import UnaccentExtension
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0008_auto_20210531_1410'),
    ]

    operations = [UnaccentExtension()]
