# Generated by Django 3.2 on 2021-06-01 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0008_auto_20210531_1410'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='url_id',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
