# Generated by Django 3.2 on 2021-06-01 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0009_auto_20210601_1648'),
        ('recipe', '0010_remove_recipe_license'),
    ]

    operations = [
    ]
