# Generated by Django 3.2.2 on 2021-11-09 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0012_alter_recipe_video_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='text_associate',
            field=models.TextField(default='', max_length=512),
        ),
    ]
