# Generated by Django 3.2.2 on 2021-11-09 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0013_recipe_text_associate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='text_associate',
            field=models.TextField(blank=True, max_length=512, null=True),
        ),
    ]
