# Generated by Django 3.2.2 on 2021-11-18 10:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipe', '0014_alter_recipe_text_associate'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='likes',
            field=models.ManyToManyField(related_name='recipe', to=settings.AUTH_USER_MODEL),
        ),
    ]
