# Generated by Django 3.2.2 on 2021-11-18 20:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipe', '0016_alter_recipe_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='favorites',
            field=models.ManyToManyField(related_name='recipe_favorite', to=settings.AUTH_USER_MODEL),
        ),
    ]
