# Generated by Django 3.2.2 on 2021-11-19 14:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipe', '0019_auto_20211119_1435'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentrecipe',
            name='likes',
            field=models.ManyToManyField(related_name='comment_like', to=settings.AUTH_USER_MODEL),
        ),
    ]
