# Generated by Django 3.2.2 on 2021-11-19 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0020_commentrecipe_likes'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CommentRecipe',
        ),
    ]
