# Generated by Django 3.2.2 on 2021-11-23 09:42

from django.db import migrations, models
import recipe.models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0021_delete_commentrecipe'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='video',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to=recipe.models.get_media_path),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='video_url',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
