# Generated by Django 3.2.2 on 2021-11-23 21:44

from django.db import migrations, models
import recipe.models
import utils.validator


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0022_auto_20211123_0942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.FileField(blank=True, default='', max_length=255, upload_to=recipe.models.get_media_path, validators=[utils.validator.file_size_image]),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='video',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to=recipe.models.get_media_path, validators=[utils.validator.file_size_video]),
        ),
    ]
