# Generated by Django 3.2.9 on 2021-12-02 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0025_auto_20211130_1025'),
    ]

    operations = [
      migrations.RunSQL("UPDATE recipe_recipe SET image = regexp_replace( image, 'recipe\/.*\/', 'recipe/admin/', 'g')")
    ]
