# Generated by Django 3.2.9 on 2021-12-02 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0025_auto_20211130_1025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='video_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
