# Generated by Django 3.2.9 on 2021-12-27 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0026_alter_recipe_video_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='is_featured',
            new_name='is_display_home',
        ),
        migrations.AlterField(
            model_name='recipe',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='video_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
