# Generated by Django 3.2.9 on 2022-02-03 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0027_auto_20211227_1152'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='meta_description_seo',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='recipe',
            name='title_seo',
            field=models.TextField(default=''),
        ),
    ]