# Generated by Django 3.2.9 on 2022-03-03 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0029_migrate_seo'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='nbr_view',
            field=models.IntegerField(default=0),
        ),
    ]
