# Generated by Django 3.2.9 on 2022-03-10 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0030_recipe_nbr_view'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='notes_from_author',
            field=models.TextField(default=''),
        ),
    ]
