# Generated by Django 3.2.9 on 2021-12-02 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0033_recipe_substances'),
    ]

    operations = [
      migrations.RunSQL("UPDATE recipe_recipe  SET price_min = '2', price_max = '3', money_saved = '2', plastic_saved = '28' WHERE id = 'c44422cc-8dfd-463d-967f-444c7c055ec7';")
    ]
