# Generated by Django 3.2.9 on 2022-03-15 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0034_recipe_update_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='money_saved',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='nbr_view',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='plastic_saved',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='price_max',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='price_min',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
