# Generated by Django 3.2.9 on 2022-03-23 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0037_migrate_kpi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='video_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
