# Generated by Django 3.2.9 on 2022-03-23 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tag', '0003_alter_tag_ingredient_cuisine'),
        ('recipe', '0038_alter_recipe_video_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recipe_category', to='tag.category'),
        ),
    ]
