# Generated by Django 3.2.9 on 2022-04-05 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0041_made'),
    ]

    operations = [
        migrations.AlterField(
            model_name='made',
            name='amount',
            field=models.IntegerField(),
        ),
    ]
