version: '3.8'
services:
  nginx:
    container_name: core_web
    restart: on-failure
    image: jonasal/nginx-certbot:latest
    volumes:
      - ./nginx/nginx.conf/nginx.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/app/static
      - ./react/build:/var/www/react
      - nginx_secrets:/etc/letsencrypt
    env_file:
      - .env.nginx
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - web
  web:
    container_name: core_app
    restart: always
    build: ./
    command: >
      sh -c "python manage.py collectstatic --no-input && python manage.py migrate &&
          gunicorn greenit.wsgi:application --bind 0.0.0.0:5000"
    volumes:
      - .:/app
      - static_volume:/app/static
    ports:
      - 5000:5000
    env_file:
      - ./.env.prod

volumes:
  static_volume:
  nginx_secrets: