version: '3.8'
services:
  nginx:
    container_name: core_web
    restart: always
    image: nginx:stable
    volumes:
      - ./nginx/nginx.beta.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/app/static
      - ./react/build:/var/www/react
    ports:
      - "80:80"
    depends_on:
      - web
  web:
    container_name: core_app
    restart: always
    build: ./
    command: >
      sh -c "python manage.py collectstatic --no-input &&
          gunicorn greenit.wsgi:application --bind 0.0.0.0:5000"
    volumes:
      - .:/app
      - static_volume:/app/static
    ports:
      - 5000:5000
    env_file:
      - ./.env.beta
  db:
    container_name: core_db
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    env_file:
      - ./.env.dev
    environment:
      - POSTGRES_USER=greenit_user
      - POSTGRES_PASSWORD=greenit_psw
      - POSTGRES_DB=greenit
volumes:
  postgres_data:
  static_volume: