version: '3.8'
services:
  nginx:
    container_name: core_web
    restart: always
    image: nginx:stable
    volumes:
      - ./nginx/nginx.beta.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/app/static
    ports:
      - "80:80"
    depends_on:
      - web
  web:
    container_name: core_app
    restart: always
    build: ./
    command: >
      sh -c "sudo python manage.py collectstatic --no-input && sudo python manage.py migrate &&
          sudeo gunicorn greenit.wsgi:application --bind 0.0.0.0:5000"
    volumes:
      - .:/app
      - static_volume:/app/static
    ports:
      - 5000:5000
    env_file:
      - ./.env.beta

volumes:
  static_volume: