version: '3.8'
services:
  web:
    container_name: core_app
    restart: always
    build: ./
    command: >
      sh -c "python manage.py collectstatic --no-input && python manage.py migrate &&
          gunicorn greenit.wsgi:application --bind 0.0.0.0:5000"
    volumes:
      - .:/app
      - static_volume:/app/static
    ports:
      - 5000:5000
    env_file:
      - ./.env.prod
  nginx-proxy:
    container_name: nginx-proxy
    build: nginx
    restart: always
    ports:
      - 443:443
      - 80:80
    volumes:
      - static_volume:/app/static
      - ./react/build:/var/www/react
      - certs:/etc/nginx/certs
      - html:/usr/share/nginx/html
      - vhost:/etc/nginx/vhost.d
      - /var/run/docker.sock:/tmp/docker.sock:ro
    depends_on:
      - web
  nginx-proxy-letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    env_file:
      - ./.env.prod.proxy-companion
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - certs:/etc/nginx/certs
      - html:/usr/share/nginx/html
      - vhost:/etc/nginx/vhost.d
      - acme:/etc/acme.sh
    depends_on:
      - nginx-proxy

volumes:
  static_volume:
  vhost:
  html:
  acme:
  certs: