# Generated by Django 3.2.9 on 2021-12-02 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tag', '0002_auto_20211118_2146'),
    ]

    operations = [
      migrations.RunSQL("UPDATE tag_tag SET name='Avec les ingrédients de la cuisine' WHERE id='b7684c10-2feb-48c0-ba54-d009b08cab47' RETURNING 'id', 'name', 'created_at', 'updated_at';")
    ]
