# Generated by Django 3.2.9 on 2022-09-29 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tag', '0005_is_for_market'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Is_for_market',
        ),
    ]
