# Generated by Django 3.1.5 on 2021-02-10 18:10

from django.db import migrations, models
import utensils.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tags', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Utensil',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40)),
                ('description', models.CharField(max_length=256)),
                ('image', models.FileField(blank=True, max_length=255, null=True, upload_to=utensils.models.get_cover_path)),
                ('tags', models.ManyToManyField(to='tags.Tag')),
            ],
        ),
    ]
