# Generated by Django 3.1.7 on 2021-03-10 14:31

import uuid

import django.db.models.deletion
from django.db import migrations, models

import ingredient.models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ('name', models.CharField(max_length=40)),
                ('description', models.CharField(max_length=256)),
                (
                    'image',
                    models.FileField(
                        blank=True,
                        max_length=255,
                        null=True,
                        upload_to=ingredient.models.get_image_path,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name='IngredientAmount',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ('amount', models.CharField(max_length=16)),
                (
                    'ingredient',
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to='ingredient.ingredient',
                    ),
                ),
            ],
        ),
    ]
