# Generated by Django 3.1.7 on 2021-03-10 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ingredient', '0002_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='amount',
            name='ingredient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ingredient_amount', to='ingredient.ingredient'),
        ),
    ]
