# Generated by Django 3.1.7 on 2021-03-10 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0004_auto_20210310_1332'),
        ('ingredient', '0003_amount_ingredient'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Amount',
            new_name='IngredientAmount',
        ),
    ]
