# Generated by Django 3.2.9 on 2021-15-03 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredient', '0006_auto_20220315_1615'),
    ]

    operations = [
      migrations.RunSQL("UPDATE ingredient_ingredient  SET name = 'Tensioactifs SCI', description = 'Le tensioactif SCI (Sodium Cocoyl Isethionate) est un agent lavant doux. particulièrement pour les shampooings solides. Il est suffisamment doux pour nettoyer les cuirs chevelus les plus sensibles. Son utilisation est saine pour l’homme et n’impacte pas la faune et la flore une fois le traitement des eaux usées. Il fait toutefois débat lors de sa fabrication, l’oxyde d’éthylène présent dans sa composition est toxique pour l’homme et l’environnement. ', alternative = 'Plusieurs options possibles si on opte pour des tensioactifs d’origines naturels : Sodium Lauryl Sulfoacetate (SLSA), Sodium Coco Sulfate (SCS). Il existe d’autres tensioactifs naturels liquides qui ne seront pas adaptés pour les produits solides. Leurs méthodes de fabrication portent à débat, mais nous considérons que c’est moins pire que les tensioactifs issus du pétrole qu’on retrouve en grande majorité en supermarché.' WHERE id = '3e05162a-f743-497e-a950-7f142e82f17d';"),
      migrations.RunSQL("UPDATE ingredient_ingredient  SET name = 'Eau', description = 'L’eau est utilisée comme support de préparation. On l’utilise pour alléger la texture du produit, à la rendre fluide, ou à véhiculer les actifs hydrophiles de la formule.', alternative = 'L’eau peut-être remplacée par des hydrolats de ton choix, en fonction de tes besoins. Attention toutefois, certains hydrolats ne se chauffent pas.' WHERE id = '4c68823c-f1e0-4be2-bc92-82842bc92e28';"),
      migrations.RunSQL("UPDATE ingredient_ingredient  SET name = 'Beurre de karité', description = 'L’incontournable du DIY ! Le beurre de karité protège et cicatrise : il combat les agressions extérieures et réduit les sensibilités. Des études prouvent même que le beurre de karité protège de certains rayons UV. Il est nourrissant et hydratant : il renforce notre barrière cutanée et limite les pertes naturelles en eau. Il est beaucoup utilisé pour les lèvres gercées et les crevasses. Bourré en vitamines E, le beurre de karité est un excellent antioxydant ! Enfin, il pénètre rapidement dans l’épiderme pour action rapide et durable.', alternative = 'De la même espèce, le beurre de karité nilotica offre une texture plus souple. On peut le substituer à d’autres beurres végétaux : cacao, mangue…' WHERE id = 'f8fad675-0227-4d12-9392-0e66dd210e24';"),
      migrations.RunSQL("UPDATE ingredient_ingredient  SET name = 'Poudre de Lotus', description = 'La poudre de Lotus est utilisée pour les soins visages notamment pour les peaux à imperfections : elle agit sur la taille des pores et rend la peau plus lumineuse.', alternative = 'Pour une action purifiante, tu peux aussi utiliser l’argile verte !' WHERE id = 'dc3d4e64-8722-437d-aabf-21021af1912e';"),
      migrations.RunSQL("UPDATE ingredient_ingredient  SET name = 'Fragrances', description = 'Elles sont utilisées uniquement pour leurs odeurs !', alternative = 'On peut remplacer les fragrances par des huiles essentielles dans la mesure où elles peuvent être utilisées par voie cutanée avec un support ET que leurs posologies et effets aient été vérifiées au préalable).' WHERE id = '9f98a66e-539b-4a60-b88c-60b86e7a540e';"),
    ]
