# Generated by Django 3.2.9 on 2022-09-26 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredient', '0009_ingredientathomeuser_ingredientshoppinglistuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='price',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='producer',
            field=models.TextField(blank=True, null=True),
        ),
    ]
