# Generated by Django 3.2.9 on 2022-09-07 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredient', '0009_ingredientathomeuser_ingredientshoppinglistuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='purchase_link',
            field=models.TextField(null=True),
        ),
    ]
