# Generated by Django 3.2.9 on 2022-09-28 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tag', '0003_alter_tag_ingredient_cuisine'),
        ('ingredient', '0010_auto_20220926_2007'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ingredient_category', to='tag.category'),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='contenance',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='indication',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='information_market',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='is_for_market',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='precaution',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='rating',
            field=models.TextField(blank=True, null=True),
        ),
    ]
