# Generated by Django 3.2.9 on 2022-09-28 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ingredient', '0012_auto_20220928_1427'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='purchase_link',
        ),
    ]
