# Generated by Django 3.2.9 on 2022-09-29 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredient', '0013_remove_ingredient_purchase_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='url_id',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
