# Generated by Django 3.2.9 on 2022-10-01 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ingredient', '0016_ingredient_url_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='url_id',
        ),
    ]
