# Generated by Django 3.2.9 on 2022-10-04 10:40

from django.db import migrations, models
import ingredient.models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredient', '0017_remove_ingredient_url_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='image_optional2',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to=ingredient.models.get_image_path),
        ),
    ]
