# Generated by Django 3.2.9 on 2022-11-16 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredient', '0019_ingredient_image_optional3'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='purchase_link',
            field=models.TextField(blank=True, null=True),
        ),
    ]
