# Generated by Django 3.1.6 on 2021-02-18 15:26

import uuid

import utensil.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tag', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Utensil',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ('name', models.CharField(max_length=40)),
                ('description', models.CharField(max_length=256)),
                (
                    'image',
                    models.FileField(
                        blank=True,
                        max_length=255,
                        null=True,
                        upload_to=utensil.models.get_image_path,
                    ),
                ),
                ('tags', models.ManyToManyField(to='tag.Tag')),
            ],
        ),
    ]
