# Generated by Django 3.1.7 on 2021-03-10 13:46

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('utensil', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UtensilAmount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.CharField(max_length=16)),
                ('utensil', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='utensil_amount', to='utensil.utensil')),
            ],
        ),
    ]
