# Generated by Django 3.2.9 on 2022-03-10 14:01

from django.db import migrations, models
import utensil.models


class Migration(migrations.Migration):

    dependencies = [
        ('utensil', '0003_auto_20211118_2146'),
    ]

    operations = [
        migrations.AddField(
            model_name='utensil',
            name='image',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to=utensil.models.get_image_path),
        ),
    ]
