# Generated by Django 3.1.5 on 2021-02-10 18:10

import django.core.validators
from django.db import migrations, models
import recipes.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('video_url', models.URLField()),
                ('language', models.CharField(choices=[('FR', 'French'), ('EN', 'English'), ('DE', 'German')], default='FR', max_length=2)),
                ('license', models.CharField(choices=[('PlaceholderA', 'Placeholder1'), ('PlaceholderB', 'Placeholder2')], default='PlaceholderA', max_length=12)),
                ('image', models.FileField(blank=True, max_length=255, null=True, upload_to=recipes.models.get_cover_path)),
                ('rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('difficulty', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', max_length=12)),
                ('duration', models.IntegerField()),
            ],
        ),
    ]
