# Generated by Django 3.2.9 on 2021-15-03 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('substance', '0002_rename_group_substance_group_subs'),
    ]

    operations = [
        
       migrations.RunSQL('CREATE EXTENSION IF NOT EXISTS "uuid-ossp";'),

      migrations.RunSQL("INSERT INTO substance_substance (id, name, group_subs, effect) VALUES "+ 
                        "(uuid_generate_v4(), 'Butylphenyl methylpropional', 'Agent parfumant', 'Allergènes règlementés en Europe, perturbateur endocrinien suspecté'), " +
                        "(uuid_generate_v4(), 'Hexyl cinnamal', 'Agent parfumant', 'Allergènes règlementés en Europe et présent naturellement dans les huiles essentielles'), " +
                        "(uuid_generate_v4(), 'Geraniol', 'Agent parfumant', 'Allergènes règlementés en Europe et présent naturellement dans les huiles essentielles'), " +
                        "(uuid_generate_v4(), 'Limonene', 'Agent parfumant', 'Allergènes règlementés en Europe et présent naturellement dans les huiles essentielles'), " +
                        "(uuid_generate_v4(), 'Linalool', 'Agent parfumant', 'Allergènes règlementés en Europe et présent naturellement dans les huiles essentielles'), " +
                        "(uuid_generate_v4(), 'Methylisothiazolinone', 'Conservateur synthétique', 'Allergènes puissants et interdits dans les produits non rincés depuis 2017'), " +
                        "(uuid_generate_v4(), 'Phenoxyethanol', 'Conservateur / Alcool', 'Toxicité pour les bébés suspectée, allergènes suspectés, impactant la reproduction suspectée'); ")
    ]
