# Generated by Django 3.1.5 on 2021-03-25 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='recipes',
        ),
    ]
