# Generated by Django 3.2.2 on 2021-11-06 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_user_dob'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='done_recipes',
        ),
        migrations.RemoveField(
            model_name='user',
            name='liked_recipes',
        ),
    ]
