# Generated by Django 3.2.2 on 2021-11-15 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20211110_1429'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_category_age',
            field=models.CharField(choices=[('-', '-'), ('young', 'Young'), ('young_adult', 'Young adult'), ('adult', 'Adult'), ('senior', 'Senior')], default='-', max_length=15),
        ),
        migrations.AddField(
            model_name='user',
            name='user_category_lvl',
            field=models.CharField(choices=[('-', '-'), ('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='-', max_length=12),
        ),
        migrations.AddField(
            model_name='user',
            name='user_want_from_greenit',
            field=models.CharField(choices=[('-', '-'), ('shared_talk', 'Shared talk'), ('meet', 'Meet'), ('find_inspiration', 'Find inspiration')], default='-', max_length=16),
        ),
    ]
