# Generated by Django 3.2.2 on 2021-11-16 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20211115_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_category_age',
            field=models.CharField(choices=[('null', 'null'), ('young', 'Young'), ('young_adult', 'Young adult'), ('adult', 'Adult'), ('senior', 'Senior')], default='null', max_length=15),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_category_lvl',
            field=models.CharField(choices=[('null', 'null'), ('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='null', max_length=12),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_want_from_greenit',
            field=models.CharField(choices=[('null', 'null'), ('shared_talk', 'Shared talk'), ('meet', 'Meet'), ('find_inspiration', 'Find inspiration')], default='null', max_length=16),
        ),
    ]
