# Generated by Django 3.2.2 on 2021-11-26 11:44

from django.db import migrations, models
import user.models
import utils.validator


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_auto_20211118_2146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image_profile',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to=user.models.get_media_path, validators=[utils.validator.file_size_image]),
        ),
    ]
