# Generated by Django 3.2.9 on 2022-02-17 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_user_photo_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id_facebook',
            field=models.BigIntegerField(db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='id_google',
            field=models.BigIntegerField(db_index=True, null=True),
        ),
    ]
