# Generated by Django 3.2.9 on 2022-03-07 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0017_auto_20220228_1442'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='urls_social_media',
            field=models.JSONField(default=dict),
        ),
    ]
