# Generated by Django 3.2.9 on 2022-03-07 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0018_user_urls_social_media'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_creator_profil',
            field=models.BooleanField(default=False),
        ),
    ]
