# Generated by Django 3.2.9 on 2022-03-07 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0019_user_is_creator_profil'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='biographie',
            field=models.TextField(default=''),
        ),
    ]
