# Generated by Django 3.2.9 on 2022-03-08 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0020_user_biographie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='biographie',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_creator_profil',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='urls_social_media',
            field=models.JSONField(default=dict, null=True),
        ),
    ]
