# Generated by Django 3.2.9 on 2022-03-09 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0021_auto_20220308_0950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='biographie',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
