# Generated by Django 3.2.9 on 2022-03-09 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0022_alter_user_biographie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='urls_social_media',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
