# Generated by Django 3.2.9 on 2022-03-17 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0018_change_path_image'),
        ('user', '0023_alter_user_urls_social_media'),
    ]

    operations = [
    ]
