# Generated by Django 3.2.9 on 2022-03-22 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0024_merge_20220317_1649'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_want_from_greenit',
        ),
    ]
