# Generated by Django 3.2.9 on 2022-05-05 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0026_auto_20220322_0719'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_beginner_box',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
