# Generated by Django 3.2.9 on 2022-08-10 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredient', '0009_ingredientathomeuser_ingredientshoppinglistuser'),
        ('user', '0029_user_particularity_search'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ingredient_at_home_user',
            field=models.ManyToManyField(blank=True, related_name='ingredient_ingredientathomeuser', through='ingredient.IngredientAtHomeUser', to='ingredient.Ingredient'),
        ),
        migrations.AddField(
            model_name='user',
            name='ingredient_shopping_list_user',
            field=models.ManyToManyField(blank=True, related_name='ingredient_ingredientshoppinglistuser', through='ingredient.IngredientShoppingListUser', to='ingredient.Ingredient'),
        ),
    ]
