# Generated by Django 3.2.9 on 2022-07-26 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredient', '0009_ingredientathomeuser_ingredientshoppinglistuser'),
        ('user', '0029_user_particularity_search'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ingredientsAtHomeUser',
            field=models.ManyToManyField(blank=True, related_name='ingredient_ingredientathomeuser', to='ingredient.Ingredient'),
        ),
        migrations.AddField(
            model_name='user',
            name='ingredientsShoppingListUser',
            field=models.ManyToManyField(blank=True, related_name='ingredient_ingredientshoppinglistuser', to='ingredient.Ingredient'),
        ),
    ]
